/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IReferee {
    function createChallenge(uint64 seed, uint64 start, uint64 end, address season) external returns (uint256);

    function verify(uint256 id, bytes calldata inputs) external view returns (uint256);

    function submit(uint256 id, bytes calldata inputs, uint256 claimed) external returns (uint256);

    function numChallenges() external view returns (uint256);

    function challengeSeed(uint256 id) external view returns (uint256);

    function challengeWindow(uint256 id) external view returns (uint256, uint256);

    function best(uint256 id, address player) external view returns (uint256);

    function top(uint256 id, uint256 i) external view returns (address, uint256);

    error BadWindow();

    error ChallengeNotFound(uint256);

    error InvalidInputs();

    error ScoreMismatch(uint32);

    error NotInWindow(uint64, uint64, uint64);
}
